version: '3'
services:
  api:
    build: .
    ports:
      - 4000:4000
    links:
      - postgres
    volumes:
      - .:/app
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uncharted
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
